### ISSUE TITLE
Blog main page order posts

### ISSUE THREAD

**Issue by air-guillaume** [getgrav/grav-theme-receptar#7]
Hi, it's me again :)

I'm wondering why my posts are not in the proper order in the main front page. I have : 

00.restaurant
01.team
02.menu
03.contact

But in the front page (not the menu, it is correct there) I have : 
- Contact
- Restaurant
- Team
- Menu

Any advise for this ? Would be appreciated.

**Comment by flaviocopes** [comment]
If you're using the Receptar Skeleton, they are ordered by date as the home page is a blog page.
Need to check the ordering set on the `01.blog/blog.md` page:

```
content:
    items: @self.children
    order:
        by: date
        dir: desc
    limit: 6
    pagination: true
```

thus, pages are ordered by date. You can change this in the page markdown file, or via Admin, to order by title: http://learn.getgrav.org/content/collections#ordering-options
